AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - config/initializers/devise.rb
    - db/**/*
    - spec/*_helper.rb
    - config/**/*
Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/AbcSize:
  Max: 20
Style/Documentation:
  Enabled: false
Rails:
  Enabled: true